added polyfill to fix Microsoft Edge script error
FreifunkVogtland/gluon pull request #1
Opened 2017-01-12 21:16 UTC by altima

MS Edge did not work with info page, because on missing EventSource in JavaScript core. So we need to add a polyfill for that.

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/104894/

2017-01-12 21:16 UTC, altima commented
With this fix the nextnode view will also work on Windows Mobile 10

2017-01-13 07:20 UTC, ecsv commented
Sorry, I have no access to the server and cannot install anything. I will therefore reassign it to @SunboX

2017-01-13 07:23 UTC, ecsv commented
@altima Forget my last comment. I was assuming it is for the meshviewer/hopglass.

Can you please forward this patch to freifunk-gluon

2017-01-13 07:26 UTC, ecsv requested changes

2017-01-13 07:26 UTC, ecsv commented on package/gluon-status-page/src/index.html.m4
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/event-source-polyfill/0.0.7/eventsource.min.js</script> <!-- polyfill -->
This doesn't look like valid HTML

2017-01-13 08:18 UTC, altima commented on package/gluon-status-page/src/index.html.m4
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/event-source-polyfill/0.0.7/eventsource.min.js</script> <!-- polyfill -->
oh, sorry, maybe I forgot to mark the rest from my proxy...

2017-01-13 08:36 UTC, altima commented on package/gluon-status-page/src/index.html.m4
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/event-source-polyfill/0.0.7/eventsource.min.js</script> <!-- polyfill -->
fixed

2017-01-13 08:50 UTC, merged